unbind '"'
unbind %
set -g prefix C-b
bind C-b send-prefix

bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D
bind h split-window -h
bind v split-window -v
bind q kill-pane
set -g default-shell /bin/zsh

bind r source-file ~/.tmux.conf \; display "Configurazione ricaricata!"

